### ISSUE TITLE
pkpass not imported into wallet - Validator says "not signed by Apple"

### ISSUE THREAD

**Issue by wildhart** [alexandercerutti/passkit-generator#108]
I'm able to generate and sign a .pkpass file using this library and comprehensive instructions in the wiki - thanks very much.

However, when I import the pass into Apple Wallet it doesn't do anything.

Also, if I try to validate the pkpass using https://pkpassvalidator.azurewebsites.net/ it reports that the pass isn't signed by Apple and that the PassKit certifcate has an incorrect value:

![image](https://user-images.githubusercontent.com/12505024/160302527-ee0d8bcb-4049-42e5-be56-1c27dd0008d2.png)

Question: would you expect passes generated by this library to pass all these validation requirements in [pkpassvalidator](https://pkpassvalidator.azurewebsites.net/)

**Comment by alexandercerutti** [comment]
Hey @wildhart, thanks for using passkit-generator!

I've never used pkpassvalidator nor do I know how it works but, as per #105, Apple recently changed from WWDR G1 to WWDR G4. When that discussion happened, pkpassvalidator wasn't yet updated to support G4 certificates. You can look at this issue on [pkpassvalidator's github](https://github.com/tomasmcguinness/pkpassvalidator/issues/15).

So, since I didn't create pkpassvalidator, I do not expect passes generated with passkit-generator to pass all points in pkpassvalidator, even if (I guess) those points are the minimum required to make a pass work on some of the possible Apple platforms. I decided to leave a certain grade of freedom (or maybe _entropy_?) to whoever uses this library.

Also, please note that passkit-generator validation is limited to props and a few things more. For example, if no icon is detected, a warning will be printed in logs, but generation won't be stopped. These might be "hot points" for the next version (for better integration with websites and generation services, for example).

About your problem, have you tried to debug and see what's wrong, through [the guide in wiki](https://github.com/alexandercerutti/passkit-generator/wiki/Troubleshooting-(Self-help))?

Let me know!

**Comment by alexandercerutti** [comment]
Hey @wildhart, do you have any updates or can we close this? 😄

**Comment by wildhart** [comment]
Hi @alexandercerutti, unfortunately our client cancelled this Apple Wallet feature so I don't time to look into this any further.  I'll close.
