### ISSUE TITLE
Cannot proceed creating the pass because transitType is missing on your boardingPass.

### ISSUE THREAD

**Issue by Songkeys** [alexandercerutti/passkit-generator#137]
To reproduce, just use the example here: https://github.com/alexandercerutti/passkit-generator/blob/11cfe99cccd27438edccc314aec044f6373f9fdf/examples/models/exampleBooking.pass/pass.json 

Load the model directly as shown in the readme:

```ts
	const pass = await PKPass.from({
		model: "./passModels/myFirstModel.pass",
		certificates: {
			wwdr,
			signerCert,
			signerKey,
			signerKeyPassphrase
		},
	});
```

So I added `transitType` in `boardingPass` in `pass.json`:

```ts
	"boardingPass": {
		"transitType": "PKTransitTypeGeneric"
	}
```

Still the same error.

So I printed out the PKPass instance:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/22665058/229260967-8e34b101-4580-4620-bd75-c6f3919e2660.png">

The `boardingPass` got overwritten. I think this is caused by this line:

https://github.com/alexandercerutti/passkit-generator/blob/11cfe99cccd27438edccc314aec044f6373f9fdf/src/PKPass.ts#L387

I'm confused.

**Comment by alexandercerutti** [comment]
Hey there @Songkeys, thanks for using `passkit-generator`!
Can you share your code for confirmation? So I can understand better the context and form an opinion.

Let me know.

**Comment by Songkeys** [comment]
Hi @alexandercerutti . This is an excellent project! Thank you so much for your hard work! 

Here is my code - please let me know if there's anything else I can do to help. :)

```ts
import path from "path";
import fs from "fs";
import pkg from "passkit-generator";
const { PKPass } = pkg;

async function main() {
	try {
		const { wwdr, signerCert, signerKey, signerKeyPassphrase } =
			getCertificatesContentsSomehow();

		const pass = await PKPass.from(
			{
				model: path.resolve(__dirname, "./models/demo.pass"),
				certificates: {
					wwdr,
					signerCert,
					signerKey,
					signerKeyPassphrase,
				},
			},
			{
				serialNumber: "AAGH44625236dddaffbda",
			}
		);

		pass.setBarcodes("36478105430"); // Random value

		const buffer = pass.getAsBuffer();
		serveTheBuffer(buffer);
	} catch (err) {
		console.error(err);
	}
}

main();
```

```json
// pass.json
{
	"formatVersion": 1,
	"passTypeIdentifier": "<....>",
	"teamIdentifier": "<....>",
	"organizationName": "<....>",
	"description": "<....>",
	"foregroundColor": "rgb(255, 255, 255)",
	"backgroundColor": "rgb(253, 123, 35)",
	"boardingPass": {
	  "transitType": "PKTransitTypeGeneric"
	}
}
```

**Comment by alexandercerutti** [comment]
@Songkeys okay so, I guess you are right. There's a lack while importing `pass.json` file. However, the issue seems to be imputable to the lines of this function instead:

https://github.com/alexandercerutti/passkit-generator/blob/11cfe99cccd27438edccc314aec044f6373f9fdf/src/PKPass.ts#L551-L566

The line you linked is indeed involved when creating the type and its fields but `transitType` is just initialized along with fields, and this is fine.

The function I linked, instead, handles the importing and setting of the type and the fields.

You can see that a push is done against the fields, but no `transitType` is included.

`transitType` should get extracted with the other fields and [the `transitType` setter](https://github.com/alexandercerutti/passkit-generator/blob/11cfe99cccd27438edccc314aec044f6373f9fdf/src/PKPass.ts#L230) should be used here to set it and validate it. However, `transitType` setter fails if the pass type is not a boarding pass, so, an additional check here might get done.

So I guess we should add it there.

Would you like to send a PR?
Let me know!

**Comment by Songkeys** [comment]
Yeah. Definitely. Give me some time. I'll make this PR later.
