### ISSUE TITLE
Model in memory

### ISSUE THREAD

**Issue by aaliakseyenka** [alexandercerutti/passkit-generator#14]
At the moment the library requires physical folder to be on the disk. It would be great to allow buffer/zip archive as an input. Issue is similar to certificates. When you working with serverless we are getting images from s3 bucket and now have to copy files to local drive. Would be great improvement to allow buffers/zip

**Comment by alexandercerutti** [comment]
Hi @aaliakseyenka.
This would be a great improvement but a bit huge to implement right now.
Also it would mean a big change for this package, as it was born with folder in mind.
I never worked with S3 nor serverless, so I don't know how it works exactly.
But we can talk about this here, I'm open to proposals and changes ☺️

**Comment by alexandercerutti** [comment]
I was thinking about requirements for this to be implemented.
Currently I don't have the possibility to _unzip_ a file. This might be the the opportunity for moving from archiver to [yazl](https://github.com/thejoshwolfe/yazl) + [yauzl](https://github.com/thejoshwolfe/yauzl).
Why I'm saying this? I'd like to reduce the weight of the library with its dependencies, which currently amounts to [7.87 MBs](https://packagephobia.now.sh/result?p=passkit-generator@1.5.8).

Yazl's weight is [57.2 KBs](https://packagephobia.now.sh/result?p=yazl), while Archiver's is [2.79 MBs](https://packagephobia.now.sh/result?p=archiver). Yauzl's is [111Kbs](https://packagephobia.now.sh/result?p=yauzl). So this would be a great improvement for this library imho. Anyway we should use yauzl with `util.promisify`, as it does not support them directly, or use a maybe a fork (?), called [yauzl-promise](https://github.com/overlookmotel/yauzl-promise) which seems to be lightweight too ([175 KBs](https://packagephobia.now.sh/result?p=yauzl-promise)).

What I wrote above, is valid if we plan to introduce zip files support. Anyway, what I wrote [in this card](https://github.com/alexandercerutti/passkit-generator/projects/1#card-19836199) for the `.load()` method, might be valid also for unzipping, as this might not be in the scope of this package, while zipping is, as a working pass is a zip file with different extension.

Whether unzipping is out of the scope on this package or not, the package should offer a method that will let the developer load the model as a set of buffers. Also, each buffer should come with a file name/path to let the library replay the whole structure.

I think this might be one of the solution for this:
```javascript
.fromModel({
    "thumbnail.png": <Buffer ...>,
    "en.lproj/thumbnail.png": <Buffer ...>
});
```

Otherwise, we might let pass the buffer structure as configuration property, along with certficates. 🤔
These are my thoughts at the moment. More will come for sure.

**Comment by alexandercerutti** [comment]
@aaliakseyenka I'm working on this. I'll let the buffers to be passed through a `string : buffer` object to be passed instead of the model path.
What do you think about? As I told above, I decided that letting a zip to be unzipped in the package, wouldn't be in its scope.

**Comment by alexandercerutti** [comment]
So, after a bit of thinking, I came up with this solution: using a Factory Function to read the model or set the buffers to merge the pass creation flow.

Sadly, this would introduce an important breaking change, as I would remove the ability to create an instance of the `Pass` class for a single function.

Soon I might create a branch with what I'll introduce next.
Of course, this will be part of v2.0.0.

**Comment by alexandercerutti** [comment]
@aaliakseyenka I don't know if you are still following this, but I just wanted to let you know that I'm going to publish the 2.0.0 beta in the next few days with this feature. I would be happy if you can test it and tell me what do you think about. 😊 Let me know.

**Comment by alexandercerutti** [comment]
v2.0.0 beta is now available.
As I said before, unzipping feature has not been integrated but you can now use buffers as a model.
I'm closing this as the beta will be merged soon.
