### ISSUE TITLE
Can't generate valid certs with OpenSSL version 3.1.4 

### ISSUE THREAD

**Issue by buren** [alexandercerutti/passkit-generator#179]
First of all thank you for an excellent library and a big thanks to the guide you've written for generating certs in the Wiki, https://github.com/alexandercerutti/passkit-generator/wiki/Generating-Certificates.

In the beginning of this year I used to to generate valid certificates that I'm now using in production. 

This week I needed to create a new Pass Type Identifier and generate new certificates, but ran into issues where I could not generate a valid pass with them. After some digging and a lot of trial and error I (finally) found what caused the issue - I was using a different version of OpenSSL than before (I'm on MacOS Sonoma 14.1).

```
$ openssl version
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)`
```

If I instead used LibreSSL 3.8.2 (installed with `brew install libressl`) everything worked as expected. I used exactly the same commands (all in the terminal, I did not use Keychain Access), the only difference was using LibreSSL vs OpenSSL. I think the reason why I did not encounter this last time is that I since have updated MacOS from 10.1 to 14.1.

The only, at least to me, visible difference between the two is the below.

When generating the private key with OpenSSL 3.1.4, I got

```
$ openssl genrsa -out mykey.pem 2048
$ cat mykey.pem
-----BEGIN PRIVATE KEY-----
# ... rest of key
```

whist using LibreSSL 3.8.2, I got 

```
$ /opt/homebrew/opt/libressl/bin/openssl genrsa -out mykey.pem 2048
$ cat mykey.pem
cat mykey.pem
-----BEGIN RSA PRIVATE KEY-----
# ... rest of key
```

Notice `BEGIN PRIVATE KEY` vs `BEGIN RSA PRIVATE KEY`. I tried with various commands using OpenSSL 3.1.4 to get `BEGIN RSA PRIVATE KEY`, but to no avail. No matter what command I tried it always gave me `BEGIN PRIVATE KEY` (for example `openssl rsa -in mykey.pem -out mykey-pkcs1.pem`.

Perhaps there are other differences between the two that is actually the root cause and the above is a non-issue, but that's the only visible difference I've found. What is obvious is that something is different.

Again, thanks for a great library and all of the work you've put into this.

---

p.s This is not a bug report, more of a FYI that perhaps can help others that might run into the same issue.

**Comment by alexandercerutti** [comment]
Hi @buren, I do remember of you, sure! Thanks for stickying with passkit-generator :D

I'm aware of some differences between OpenSSL and its fork, LibreSSL.
I've documented one of them in the same guide: https://github.com/alexandercerutti/passkit-generator/wiki/Generating-Certificates#openssl-change-of-p12-encryption-algorithm

Perhaps this could be related to the `-legacy` flag. Could you test it and let me know, please?
Thank you!

**Comment by buren** [comment]
I never used any of the steps under ["Generate certificates through MacOS"](https://github.com/alexandercerutti/passkit-generator/wiki/Generating-Certificates#generate-certificates-through-macos) since I followed ["Generate certificates through Terminal
"](https://github.com/alexandercerutti/passkit-generator/wiki/Generating-Certificates#generate-certificates-through-terminal). So I never handle any .p12 files. 

My knowledge around these things is unfortunately limited.

After creating a Pass Type Identifier:

1. Create private key
```
openssl genrsa -out mykey.pem 2048
```

2. create CSR
```
openssl req -new -key mykey.pem -out mycsr.csr -config caconfig.cnf
```

3. Upload CSR to developer.apple.com and download `pass.csr`

4. Convert `pass.cer` and WWDR to PEM
```
openssl x509 -inform DER -outform PEM -in pass.cer -out signer.pem
openssl x509 -inform DER -outform PEM -in AppleWWDRCAG4.cer -out wwdr.pem
```

**Comment by alexandercerutti** [comment]
Mine is limited too, so I go by experimentation!

Here's an interesting explanation about the differences: https://stackoverflow.com/questions/20065304/differences-between-begin-rsa-private-key-and-begin-private-key

In my tests I always use a key that, after password decryption, has `BEGIN PRIVATE KEY`, so that should be perfectly fine... there must be something else perhaps, maybe the signing algorithm, if there's one.

Before password decryption, I always have a `BEGIN ENCRYPTED PRIVATE KEY` with above all the details of the Bag (which are PKCS#8's attributes).

Also, there's a thing to consider: passkit-generator is passing through `node-forge`, which is an implementation of such algorithms. So perhaps there could be something missing in `node-forge` or in passkit-generator as well to perform a better recognition.

May I ask you to perform some tests? So we can understand better the whole picture.

1) Can you perhaps try to create a `signature` file through the terminal command in https://github.com/alexandercerutti/passkit-generator/wiki/Generating-Certificates#do-i-really-need-passkit-generator-to-create-apple-wallet-passes and tell me your results with both generated keys and zip everything together?

2) Can you attach what does it say when you do `openssl version -a`?

3) Could you please report what does the `Console.app` says when you try to open a pass created with a key that uses OpenSSL? Maybe we can found some details more by Apple.

Thank you.

**Comment by alexandercerutti** [comment]
Uhm, if I recall correctly, mine was maybe generated through `KeychainAccess.app`, which might be using LibreSSL (see #154) under the hood...

I'm reading that [OpenSSL actually supports a set of encryption algorithms, but if none is provided, no encryption will be used](https://www.openssl.org/docs/man1.0.2/man1/genrsa.html). So this should be valid for LibreSSL as well.

If I remember correctly, when issuing the p12 through Keychain Access, it requires you to set a password, so maybe an encryption is being used in mine but not in yours due to terminal.

Are you setting a `signerKeyPassphrase` perhaps?

___


Anyway, if I take my key and try to read it through [`pkey`](https://www.openssl.org/docs/man3.0/man1/openssl-pkey.html):

```sh
$ openssl pkey -in signerKey.pem
```

I get `BEGIN PRIVATE KEY`.
Versus:

```sh
$ openssl pkey -in signerKey.pem -traditional
```

I get `BEGIN RSA PRIVATE KEY`.

Nonetheless, again, both should be fine.

**Comment by buren** [comment]
Interesting.

I've written a small CLI for internal use at our company and in that it recommends using LibreSSL 3.8.2. That was the simplest solution for us. 

Must say I'm really surprised the output of different versions differ so much when using the same command. 

Perhaps it would be worth adding a small note about this in the [Wiki](https://github.com/alexandercerutti/passkit-generator/wiki/Generating-Certificates) or reference this issue to help others. 

Thanks for your help 👑

**Comment by alexandercerutti** [comment]
I will try the commands again from scretch to see any differences. I guess you won't do the tests I asked you, isn't it? :D

**Comment by buren** [comment]
I can confirm that 👇 

```
$ openssl pkey -in signerKey.pem -traditional
```

converts the key to `-----BEGIN RSA PRIVATE KEY-----` :) 

I will try to get around trying that end-to-end and verify that using that key can sign Apple Wallet passes, though that will have to be later :|

**Comment by buren** [comment]
Did you use the `-traditional` option as you suggested or without it?

**Comment by alexandercerutti** [comment]
I didn't have the need to use it

**Comment by alexandercerutti** [comment]
I'm closing this in the meantime because I don't know how to replicate the issue. I'll work on it if I'll ever experience it again or if someone else experiences this issue.

Thank you for reporting, @buren!
