### ISSUE TITLE
logoText as override Option

### ISSUE THREAD

**Issue by gweit** [alexandercerutti/passkit-generator#21]
Hi Alex,

Is there any way to override the logoText?

As far as i can see it might work through the override-options, but is not declared in schema.js. Am i on the right path?

Best, Gernot

**Comment by gweit** [comment]
i tried to add the following line in **schema.js** under **supportedOptions** and it works as expected:

**logoText: Joi.string()**

Could you please add it in one of your future updates?

**Comment by alexandercerutti** [comment]
Hi @gweit,
yes, you are right, that's the correct way. But let me tell you first the reason I did not insert it in `supportedOptions`.
When I created `passkit-generator`, the idea behind was to have different models for different scopes. Therefore, when I was in the phase of attributes choosing, I filtered the ones that can, should or must be different for each pass from the ones that should be static for each model. This was a specific design, and it shouldn't be a problem to add it.
Tell me, do you really need it? Can you tell me your use case? Thank you.

**Comment by gweit** [comment]
Hi @alexandercerutti,

Thanks for the fast reply.

You are right, and it won´t happen often that logoText will be changed - but as far as i am giving this option to the enduser it would be very cool to be able to change this one to ;)

**Comment by alexandercerutti** [comment]
@gweit I'm definitely not sure about this thing. I mean... why should you be able to change the logoText? Usually, the logo text is the text of the... logo, or the company. For this reason, I asked you to show me your use case (or what the final pass should look like in different cases).

**Comment by ianbale** [comment]
I have a use case where this is needed. UK Rail tickets have used the logo text field to display the travel date (no idea why ATOC make the decisions they do, but there is no possibility of getting them to change this). Therefore, it has to be different for every ticket. 

There is a work around, of course, simply create the JOSN file on the fly for every ticket, but since that has to be on DISK rather than in memory at the moment, that is not a great solution performance wise.

I've already got a patch to allow this to be set, along with backgroundColour (which I also need to override for some tickets).

Will get a branch setup with this shortly. Hopefully you'll accept the PR for this...

**Comment by alexandercerutti** [comment]
What's ATOC? And which are the decisions you are talking about?
About the pass in memory, it will be available in the v2 (as per #14).
About the logoText, I left this issue open on purpose, to talk about the introduction of this edit. 👍

**Comment by ianbale** [comment]
ATOC = Association of Train Operating Companies.

You really don't want to know! Money grabbing protectionists. Same everywhere...

**Comment by alexandercerutti** [comment]
I mean, are there some decisions related somehow to the pass creation and logoText integration? 😂

**Comment by ianbale** [comment]
ATOC have mandated exactly how a train ticket pass must look. Since some retailers are already using them, there is no possibility of getting that changed - ATOC NEVER listen anyway. So I'm stuck with having to use the logo text for the valid date of the pass. We also need to produce passes with different colour backgrounds. So changing that is also essential.

**Comment by alexandercerutti** [comment]
@ianbale Okay, got it. I'll introduce it soon, just because you have no other choices.

**Comment by alexandercerutti** [comment]
Published in 1.6.5, @gweit @ianbale 🎉
