### ISSUE TITLE
Issue with TypeScript 3.7.2

### ISSUE THREAD

**Issue by rweindl** [alexandercerutti/passkit-generator#44]
Hey @alexandercerutti thank you for your passkit-generator project! I currently tried running your project but receive the following error when transpiling:

```
node_modules/passkit-generator/index.d.ts:67:10 - error TS2370: A rest parameter must be of an array type.

67  beacons(...data: Schema.Beacon[] | null): this;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/passkit-generator/index.d.ts:74:12 - error TS2370: A rest parameter must be of an array type.

74  locations(...data: Schema.Location[] | null): this;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rweindl** [comment]
I think it should be:
```
	locations(...data: Schema.Location[]): this;
```
and
```
	beacons(...data: Schema.Beacon[]): this;
```

**Comment by alexandercerutti** [comment]
@rweindl Hi, thank to you for using it!
May I know how are you trying to transpile it? Because:
1) I think index.d.ts should be excluded from the transpilation since it is just an declaration type
2) I putted null in there because the value can be specifically null to reset the internal value.

Let me know 😊

**Comment by rweindl** [comment]
Hi thanks for your quick response! I just transpile it with: `tsc`. My files are in an `app/` directory. I access your framework only at one place via
```
import { createPass, createAbstractModel, AbstractModel } from 'passkit-generator';
```
The only thing I changed in the `tsconfig.json` in the test setup is:
```
"outDir": "./build",
```
When modifing the file as mentioned above it works for me.
My `tsc` version is `6.12.0`

Thank you so much for looking into it!

**Comment by alexandercerutti** [comment]
I'll do some tests with the latest typescript version this evening, because it might be possible that something changed with Typescript 3.7!

Anyway, if you downloaded my package from npm ( `npm install --save passkit-generator`), it is already compiled in plain javascript, so it do not need to be compiled again.

Is it possibile that you are trying to compile also packages in your `node_modules`, so it is matching `index.d.ts` file? It is weird it just works only changing the `outDir`.

Let me know!

P.s. it is not a framework but just a library 😄

**Comment by alexandercerutti** [comment]
Hi @rweindl, I had a moment to test with `tsc` on the project. I had some problems with imports but not the one you told me. Were you trying to compile the project in typescript or the one downloaded through npm?

Thank you

**Comment by alexandercerutti** [comment]
Hi @rweindl, any news? Have you solved?

**Comment by rweindl** [comment]
Hey @alexandercerutti thank you for your message! Unfortunately I haven't solved it yet. Will take another look on it tonight. Was focusing on something different the past days. I keep you updated!

**Comment by alexandercerutti** [comment]
Okay, thank you! 😄

**Comment by rweindl** [comment]
Hey @alexandercerutti it works on my end now too. However, I had to set in the `tsconfig.json`:
```
{
  "compilerOptions": {
     ...
     "strict": false, // When setting to true passkit-generator fails.
  }
}
```
Maybe you can explicitly set the strict option on your end once and see if you receive the same error as described above. But besides that I can live with the `strict: false` option. Thank you for taking a look into that issue! Feel free to close the issue.

**Comment by alexandercerutti** [comment]
Oh - my - d**ee**r! Actually I never used that option in my `tsconfig.json`s and never saw how it works. Using it, a lot of possible errors pop up, among the ones you told me.
A lot of "problems" are from tests, but f**k, I'm sure they work 😂
I have to check if any of them might cause a problem in production.

Anyway, so you set `strict: true` on your TS project, in your `tsconfig.json`, isn't it? You are not trying to compile again this package. It seems like your _tsc_ is trying to compile all the files `.ts` in your working directory, among which the ones in `node_modules`. Among these, there are also the `.d.ts` files, which are the declaration files only, and should not be compiled (I suppose) by Typescript compiler.

I think you should check this, because compiling __all__ the node_modules can be really heavy.

Anyway, thanks for this!
