### ISSUE TITLE
Use this server on lambda

### ISSUE THREAD

**Issue by Dicondur** [alexandercerutti/passkit-generator#51]
Hi bumped into this repo today.. quickly setup and all working awesome stuff!.. Wondering what will it take to host this as a service on a AWS lambda? Where would you suggest will be agood place to start to look for? Thanks!

**Comment by alexandercerutti** [comment]
Hi @Dicondur
Thanks for using it 😄

Actually I've never used AWS Lambdas so sadly I think I'm not able to help you in this. 😔

But if you find out how to set it up on a Lambda, please teach me and we could add an example file or a page in the wiki 😄

**Comment by Dicondur** [comment]
I have a PR for adding this example. Let me know.

**Comment by moogus** [comment]
The issue with using this on a lambda comes more from the life time of the lambda.  Generating a long standing stream is not really what lambdas are good at, they are good for simple single tasks.  The best suggestion to use this package in a lambda would be to use the lambda to create the pass and pass it to a a bucket as a depreciable asset and return a link to that asset in your response.  Kind of a post get, hope this helps.

**Comment by alexandercerutti** [comment]
Thank you @moogus. I kinda agree, they should be created and used as a blackbox to return just one pass for your data.
A thing I'd like to underline, is that Apple suggests *to not save passes*, because it is probably useless. They should instead be generated from your data every time. So, @moogus, you should add it to a bucket, download it and then delete it, isn't it? 😄
When I'll have chance to put my hands on the PR, I'll consider adding this way to generate the pass.

**Comment by Dicondur** [comment]
Yes, Passes are like snapshots of your DB table (it might not be upto date). And so I created a DynamoDB table with details that I want to show up on the pass and invoked a lamdba to create a pass from this table.

This comes in handy when you do want to implement Apple PassKit Webservices for updating the passes later too.

**Comment by ianbale** [comment]
I've been using this in a Lamba function for a year now. There are no specific problems with doing so. There are a few inconveniences - but nothing different to other libraries - eg. PDFKit which I use along side this.

I place the various PEM files in /tmp after extracting them from AWS Secrets Manager. I also write the resulting tickets to /tmp

You do need to be aware to clear /tmp at the start of the function since lambda can and do get re-used, so debris can be left from a previous invocation and with very limited /tmp space you can run out quite easily if the function is busy.

```

var eTicketPassConfig = {
  model:"./fulfil/resources/eticket",
  certificates: {
      wwdr: "./fulfil/resources/certs/AppleWWDRCA.pem",
      signerCert: "/tmp/signerCert.pem",
      signerKey: {
          keyFile: "/tmp/signerKey.pem",
          passphrase: "",
      }
  },
  shouldOverwrite: true
}


const makeOnePass = (passConfig,passData,filename,bookingReference) => {

  return new Promise(async function(resolve, reject) {

    try
    {
      let pass = await createPass(passConfig)

      pass.barcodes(passData.barcode)
      pass.expiration(passData.expiry)

      for (let key in passData.relevance)
      {
        pass[key] = passData.relevance[key]
      }

      for (let key in passData.ticketData)
      {
        let data = passData.ticketData[key]

        for (let i=0;i<data.length;i++)
        {
          pass[key].push(data[i])
        }
      }

      pass.transitType = "PKTransitTypeTrain"

      let writestream = await fs.createWriteStream(`${tempFolder}/${bookingReference}/${filename}.pkpass`)

      // Generate the stream, which gets returned through a Promise
      let stream = await pass.generate()
      stream.pipe(writestream)

      stream.on('end',() => {
        resolve()
      })

      stream.on('error',err => {
        reject(err)
      })
    }
    catch(err)
    {
      reject(err)
    }
  })    
}
```

The biggest difficulty I had was with folder containing my pass model (inc. logo image). The path in the config must be relative to the entry point of your lambda call - NOT relative to the file where you create the pass. 

My use case is producing train tickets. My "make ticket" function does a lot of things, creating a pass ticket being just one of them. So I have a lot of code organised into an array of folders. One of those being the code that does the ticket creation.

My config (in eticket/ticket.js) says:

`  model:"./models/eticket",` 

And my folder structure (greatly simplified!) is:

```
fulfilment/
  fulfil.js **** This is the function that gets called via API gateway
  models/
    ticket.pass
sdci-records/
  cw.js
  utils.js
tod/
  ticket.js
eticket/
  ticket.js

```

So, whilst the config appears to say the model is in a folder inside eticket, it is actually inside the fulfilment folder.

One way usage could be made simpler is by having an option to attach the PEM files and model object into the config rather than providing a path to the file system. Also provide a base64 representation of the logo/icon instead of having a file.

That would do away with the need to write the PEM files to disk after reading from AWS Secrets Manager. It seems wasteful to get the PEM, write to disk and then have passkit-generator immediately read it back into memory.

Having an option to have the pass returned in a buffer instead of writing it to disk could also be more efficient for me since I immediately upload the resulting data to AWS S3. I never need it on disk.

Avoiding disk use would make using it from within Lambda a little more convenient, but there are definitely no significant issues with using it in Lamda as it stands now.

**Comment by alexandercerutti** [comment]
Thank you for your precious explanation @ianbale!

> One way usage could be made simpler is by having an option to attach the PEM files and model object into the config rather than providing a path to the file system. Also provide a base64 representation of the logo/icon instead of having a file.
>
>That would do away with the need to write the PEM files to disk after reading from AWS Secrets Manager. It seems wasteful to get the PEM, write to disk and then have passkit-generator immediately read it back into memory.
>
>Having an option to have the pass returned in a buffer instead of writing it to disk could also be more efficient for me since I immediately upload the resulting data to AWS S3. I never need it on disk.
>
>Avoiding disk use would make using it from within Lambda a little more convenient, but there are definitely no significant issues with using it in Lamda as it stands now.

Are these suggestions for passkit-generator?

Let me say few things:
- I do provide a stream to avoid directly the need to save pass to disk, but actually I don't know how you can handle streams on AWS to serve the generated pass;
- You can convert, sadly not in an very easy way, a stream to a buffer;
- About the PEM, `createPass` function accepts PEM files as strings, so if you are always using the same, you can pass it the already-read content;
- About base64 as content, that might be interesting to be implemented actually, but I don't know. I have to check how this can be done; meanwhile you can provide buffers and buffer models. You can refer to migration guide of v1 to v2 [here](https://github.com/alexandercerutti/passkit-generator/wiki/Migrating-from-v1-to-v2);

Hope this is helpful. 😊

**Comment by ianbale** [comment]
THat's interesting! To be fair I've been using an older version of passkit until now, so not really investigated what is new. I'l certainly take a look at passing in the PEM files as strings instead of paths. 

I'll look at the output too, but I'd need to get pdfkit to output thew PDF to memory as well, as I need to ZIP the pass and pdfs (often several of each) into a single ZIP file to send to AWS S3. It wouldn't be helpful to have some on disk and some in memory. Will take another look at pdfkit to see if they offer that option yet.

My train ticket service (Smartix) is described here: https://www.hazardousfrog.com/smartix if you are interested.

**Comment by alexandercerutti** [comment]
This is going a bit off-topic, but yeah!
Anyway, glad to be helpful. You can refer to the [migration guide](https://github.com/alexandercerutti/passkit-generator/wiki/Migrating-from-v1-to-v2). Anyway, the link you provided me goes on Access Denied. If you want to create a showcase, you can open a new thread in [discussions](https://github.com/alexandercerutti/passkit-generator/discussions). 😄

**Comment by Dicondur** [comment]
With regards to PEM file as text:
> I place the various PEM files in /tmp after extracting them from AWS Secrets Manager. I also write the resulting tickets to /tmp

I used the below doc to extract it.
https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-using-aws-secrets-manager
=> (note ~true as secrets are always encrypted)

API associated with this if not using Serverless framework:
https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html

**Comment by ianbale** [comment]
Fixed the Smartix link. Missing the trailing slash.  AWS S3 hosting doesn't like the missing slash!

**Comment by alexandercerutti** [comment]
A Serverless / AWS example is being added in the new v3.0! Thank you all for your explanations and help!
