### ISSUE TITLE
Push new update 

### ISSUE THREAD

**Issue by onlyamir007** [alexandercerutti/passkit-generator#58]
im new wallet world could you give me URL or example how to push new updates to wallet card.
Thank you

**Comment by alexandercerutti** [comment]
Hey there, technically this shouldn't role of mine, but yes, I can give you some pointers.

You have to create a webserver that respects the endpoints specified here: https://developer.apple.com/documentation/walletpasses

Apple Documentation archive has a whole guide about creating passes and using Apple's API.
 https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Updating.html#//apple_ref/doc/uid/TP40012195-CH5-SW1

https://developer.apple.com/library/archive/documentation/PassKit/Reference/PassKit_WebService/WebService.html

Hope these will help you!
Let me know!

**Comment by onlyamir007** [comment]
Thank you so much ...

**Comment by alexandercerutti** [comment]
If you have any other questions about this topic, I'll leave this thread open for a while, so we can discuss.

**Comment by santyas** [comment]
Hello! Do you have any knowledge about updates to installed passes? I'm having trouble with the request that the pass makes to my GET route where it gets the latest changes passing authToken and "since" date. Im following the logs and params are undefined :O But otherwise I have no problems registering a new device, deleting or downloading the pkpass again.

https://developer.apple.com/forums/thread/773511

Thank you in advance @alexandercerutti  :)

**Comment by alexandercerutti** [comment]
Hi @santyas, I'm moving your message in a different conversation in order to not create useless emails to onlyamir007 :) I'll answer you there.
