### ISSUE TITLE
Node 14.13.1 package is broken

### ISSUE THREAD

**Issue by moogus** [alexandercerutti/passkit-generator#59]
Hi

Package seems to be incompatible with latest version of node

```bash
TypeError: Cannot destructure property `readdir` of 'undefined' or 'null'.
    at Object.<anonymous> (~/node_modules/passkit-generator/src/parser.js:34:53)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/node_modules/passkit-generator/src/factory.js:9:18)
    at Module._compile (module.js:653:30)
```

**Comment by alexandercerutti** [comment]
Hey there @moogus!
So, it seems it cannot find `fs.promises`. That's really weird!
I'll check as soon as possible. Thank you for reporting this!

**Comment by alexandercerutti** [comment]
I'm investigating right now with `14.13.1`, but I actually do not understand which seems to be the issue, because I cannot reproduce.
If I run `npm test` on the project, I get the compiled version of the project and the tests get executed successfully.
The same happens if I run the examples.

I was looking at the compiled code and I saw this:

```javascript
const fs_1 = __importDefault(require("fs"));
const debug_1 = __importDefault(require("debug"));
const prsDebug = debug_1.default("Personalization");
const { readdir: readDir, readFile } = fs_1.default.promises;
```

So, maybe, what's wrong is that you cannot access `.default.` but I'm not sure why.
Can you please provide me some kind of repro-case I can use to investigate?
Thank you, @moogus

**Comment by moogus** [comment]
Will try my best to reproduce it again tomorrow. 

Oddly it's fine in 14.13.1

**Comment by moogus** [comment]
I seem to have fixed it.  Had to delete my package.json and node_modules then all was good.

Thanks for looking at this
