### ISSUE TITLE
Add Buffer Model to README

### ISSUE THREAD

**Issue by sarawarnock** [alexandercerutti/passkit-generator#68]
Love this project! Super useful in the professional setting I'm working in :) The only thing that would have been helpful would be to have an example of the Buffer Model in the README or even the API docs as it took me a bit to find it in the Migration Guide! Again, thank you for all your work on this!

**Comment by alexandercerutti** [comment]
Hey there @sarawarnock!
Thank you for using passkit-generator!

I really appreciate your feedback and I agree it could be useful. I never inserted it because actually, buffers get returned from some kind of processing, but I might consider adding somewhere an example of buffer model made of incomplete code (by using, for example, "`Buffer.from([...])`", just to let you understand what I mean).

I also opened [a thread in discussions about the model creation](https://github.com/alexandercerutti/passkit-generator/discussions/64). If you want, check it out. I'd like to have as much feedback as possible 😄.

___

Since you are enjoying using passkit-generator, may I ask you to leave a star on the project? 🌟 That would be really appreciated!

**Comment by sarawarnock** [comment]
That's exactly what I was thinking! Just something to give an idea of how it would work. Finding the migration guide was a huge help for me when using that model. Created a PR just in case you want to include!
