### ISSUE TITLE
Getting error when deploying to a aws lambda for serverless usage. 

### ISSUE THREAD

**Issue by mgcox** [alexandercerutti/passkit-generator#7]
I am getting an error on line 41 of pass.js - Object.assign(this, this._parseSettings(options));
```
TypeError: Cannot read property 'reduce' of undefined
    at Object.filter (/var/task/node_modules/passkit-generator/src/schema.js:133:14)
    at Pass._parseSettings (/var/task/node_modules/passkit-generator/src/pass.js:676:31)
    at new Pass (/var/task/node_modules/passkit-generator/src/pass.js:41:28)
    at exports.handler (/var/task/index.js:13:20)
```

Any suggestions on how to debug? 
The same code works when I run it locally.

**Comment by alexandercerutti** [comment]
Hi @mgcox! To debug you should start your node process with `DEBUG=*` before. I never developed on AWS nor serverless in general, so I not sure to be fully able to help you! Anyway, I'm going to do the best I can.

If is not able to run, is because a the list is missing. The list is the object passed as parameter to `schema.filter`.

Are you passing any custom key as `overrides` when you instantiate Pass class? Reading the code, I think this might be one of the reasons.

Can I ask you to show me your code or at least the part where you instantiate the Pass class? Thank you

**Comment by alexandercerutti** [comment]
Okay, I think I was able to reproduce the error, but first let me know a thing: locally you test an example or your version? Anyway, I'm going to release a bugfix for this ASAP. Meanwhile, thank you!

**Comment by mgcox** [comment]
Yeah, I think passing through empty overrides will allow it to work. Maybe that was the problem?

Also, on a side note. Since i'm running it on a server, instead of doing stream.pipe(response) how I pass the stream to a data buffer to store in a db?

**Comment by alexandercerutti** [comment]
I think that is the problem. Does it work on AWS?

I'm going to push this fix I think in 30 minutes. I'll notify you here when available!

You have to read the stream chunk by chunk and add the chunks to an array and the use `Buffer.from`.
Maybe there are some libs that can do this job more efficiently, I don't know.

**Comment by alexandercerutti** [comment]
@mgcox I've published the update! Let me know if it works!

**Comment by mgcox** [comment]
This update fixed the issues! Great work
