### ISSUE TITLE
WordPress plugin

### ISSUE THREAD

**Issue by mxstmx** [alexandercerutti/passkit-generator#71]
Hey,
Is it possible to rewrite the code for a WordPress plugin?

Lg max

**Comment by alexandercerutti** [comment]
@mxstmx Hey there @mxstmx,
I'm not actually very much into PHP and not into Wordpress and WordPress plugin creation at all.
This is a library for node.js, but I'm sure there are other libraries for PHP that are easier to port to WordPress plugins, out there!

I cannot help you in this. If you are proficient, you can create yourself a plugin for WordPress.

Otherwise what can I suggest you is to set up a cloud function somewhere, install your project with passkit-generator in it and then call the function url whenever needed.
