### ISSUE TITLE
Misspelled key names

### ISSUE THREAD

**Issue by martip** [alexandercerutti/passkit-generator#76]
Ciao @alexandercerutti!

Thank you for this code.

I discovered a little issue: Apple defines the field dictionary key `dataDetectorTypes` (plural) as the array of detector names to use (https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/FieldDictionary.html#//apple_ref/doc/uid/TP40012026-CH4-SW6).
 
You define the key as `dataDetectorType` (singular): https://github.com/alexandercerutti/passkit-generator/blob/e1c46491d6c685fdb4dd8115fb58b37e479e5425/src/schema.ts#L374

I don't know if your choice is intentional,  but I think that it can lead to some confusion (it took me some time to figure it out).

It's not a big issue, indeed. But even if it's not going to be fixed (breaking change!), maybe this note can help someone else.

**Comment by alexandercerutti** [comment]
Hey there @martip!
Thank you for using passkit-generator!

Thank you for your report. This is definitely not intentional and I have to fix it. It is also wrong in the Schema right below.
This cannot be considered a breaking change, imho, because it can actually cause unintentional behavior when using the library.

In fact, if the schema is wrong, runtime validation fails and the library will emit an error.
If type structure is wrong, typescript emits a development error that can be ignored.

Probably no one ever used this type is such a long time.
I'll fix this as soon as possible. I'm also open to accept a Pull Request if you want. 😄

Please note that the link you looked at, is an archived documentation.
I was looking for the new documentation and, with a very big surprise, I discovered that Apple rewritten and redesigned more parts of its new Apple Wallet documentation!!

Here's the new link.

https://developer.apple.com/documentation/walletpasses/passfieldcontent

I think I'm going to do a review of the links in the documentation to the new one.

**Comment by martip** [comment]
Thank you @alexandercerutti!

Glad I helped. Unfortunately I'm an old JS guy and I'm not so fluent in TS 😔... so I'm not sending a PR. Sorry.

Thanks for the updated link to Apple docs.

Ciao

**Comment by martip** [comment]
Ops... I found another similar issue (just some lines below the previous)

https://github.com/alexandercerutti/passkit-generator/blob/e1c46491d6c685fdb4dd8115fb58b37e479e5425/src/schema.ts#L381

`ignoreTimeZone` should actually be spelled `ignoresTimeZone`.

I updated the issue title.

**Comment by alexandercerutti** [comment]
Wow, I'm surprised I never noticed such typos!! Great job!
If you find other typos, do not list them all in the title but just remove the parenthesis. 😉

**Comment by martip** [comment]
Changed the title (it was ugly, even with two keys only) 😉

**Comment by alexandercerutti** [comment]
Hmm, I started with this and I finished refactoring all the Schema system 😂

I guess it might take a bit more time because I have to write more tests to check if it is all okay!
I've added even more missing SemanticsTags.

**Comment by alexandercerutti** [comment]
Released in `v2.0.7`. Thank you very much!
