### ISSUE TITLE
How to make pass show up when you double tap the lock screen?

### ISSUE THREAD

**Issue by AWZRD** [alexandercerutti/passkit-generator#78]
The card shows up in the apple wallet app after being downloaded, but I want it to be readily available in the lock screen, how do I go about doing this? 

Thanks in advance

**Comment by alexandercerutti** [comment]
Hey there @AWZRD,
What you are looking for, is called "relevancy". It happens when:
 - User is near areas defined under `locations`
 - Time is almost the time defined under `relevantDate`.
 
 I suggest you looking at official documentation and then looking at the APIs doc. Here are the links:
 
https://developer.apple.com/documentation/walletpasses/pass
https://github.com/alexandercerutti/passkit-generator/blob/master/API.md#locations
https://github.com/alexandercerutti/passkit-generator/blob/master/API.md#relevantdate

Let me know if you need further help. 😊

**Comment by alexandercerutti** [comment]
Hey @AWZRD, did you solve it? Did I get what you were looking for?
I'm going to close this soon if no further help is needed. Thank you
