### ISSUE TITLE
README.md file is inconsistent with 3.x

### ISSUE THREAD

**Issue by socsieng** [alexandercerutti/passkit-generator#85]
I ran into some issues following the examples in the README.md file leading me to think that there were problems with either my cert or key. Specifically:

```diff
const pass = PKPass.from({
	model: "./passModels/myFirstModel",
	certificates: {
-		wwdr: "./certs/wwdr.pem",
-		signerCert: "./certs/signercert.pem",
-		signerKey: "./certs/signerkey.pem",
+		wwdr: fs.readFileSync("./certs/wwdr.pem"),
+		signerCert: fs.readFileSync("./certs/signercert.pem"),
+		signerKey: fs.readFileSync("./certs/signerkey.pem"),
		signerKeyPassphrase: "123456"
	},
}, {
	// keys to be added or overridden
	serialNumber: "AAGH44625236dddaffbda"
});
```

Another minor detail is that `PKPass.from` returns a `Promise` so the code needs a little tweak to include `await`.

**Comment by alexandercerutti** [comment]
Hey @socsieng,
yeah, my bad! I made a bit of confusion in the conversion of examples! 😅

Yes, as you found, certificates are not read anymore by the library but you have to read them first. I'll fix the Readme asap.

`PKPass.from` returns a Promise on purpose. That's because it has to read the model from the File System. `PKPass.from` is not the only way to create a Pass. If you already have one in memory, you can call the constructor (like `new PKPass(...)`).

Thanks for making me aware of this silly certificates error! I'm available for any other questions. 😄

**Comment by alexandercerutti** [comment]
Done! Now it should be clearer (at least, I hope that's so)! Thank you for your report again 💚
